/*
 * InstantIoT Server — self-hosted IoT relay for makers.
 * Copyright (C) 2026 Djoufack Tsobeng Jean Loick (InstantIoT)
 * Author: Djoufack Tsobeng Jean Loick (@jeanloick_dt)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// widget/data/SqliteWidgetRepository.kt
package com.jeanloickdt.widget.data

import com.jeanloickdt.widget.domain.WidgetRepository
import com.jeanloickdt.widget.domain.WidgetRow
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.transactions.transaction

class SqliteWidgetRepository : WidgetRepository {

    // ============================================================
    // Register a widget — id generated by the app
    // ============================================================
    override fun register(id: String, projectId: String, ownerId: String, type: String) {
        transaction {
            WidgetTable.insert {
                it[WidgetTable.id]          = id
                it[WidgetTable.projectId]   = projectId
                it[WidgetTable.ownerId]     = ownerId
                it[WidgetTable.type]        = type
                it[WidgetTable.lastPayload] = null
                it[WidgetTable.lastSeenAt]  = null
            }
        }
    }

    // ============================================================
    // Idempotent register — auto-register from DeviceRelay
    // Uses INSERT OR IGNORE via SQLite ignoreAndReturnGeneratedKeys
    // ============================================================
    override fun registerIfAbsent(
        id: String,
        projectId: String,
        ownerId: String,
        type: String
    ): Boolean {
        return transaction {
            // `insertIgnore` → no-op if (id) already exists (primary key).
            // We never overwrite: the lastPayload/lastSeenAt fields of an
            // existing widget are left untouched.
            val inserted = WidgetTable.insertIgnore {
                it[WidgetTable.id]          = id
                it[WidgetTable.projectId]   = projectId
                it[WidgetTable.ownerId]     = ownerId
                it[WidgetTable.type]        = type
                it[WidgetTable.lastPayload] = null
                it[WidgetTable.lastSeenAt]  = null
            }
            // `insertIgnore` returns an InsertStatement; insertedCount > 0
            // → a row was created.
            inserted.insertedCount > 0
        }
    }

    // ============================================================
    // Find a widget by its id
    // ============================================================
    override fun findById(id: String): WidgetRow? {
        return transaction {
            WidgetTable
                .selectAll()
                .where { WidgetTable.id eq id }
                .singleOrNull()
                ?.toWidgetRow()
        }
    }

    // ============================================================
    // List all widgets of a project
    // ============================================================
    override fun findAllByProject(projectId: String): List<WidgetRow> {
        return transaction {
            WidgetTable
                .selectAll()
                .where { WidgetTable.projectId eq projectId }
                .map { it.toWidgetRow() }
        }
    }

    // ============================================================
    // Update last_payload + last_seen_at — relay only
    // ============================================================
    override fun updateLastPayload(id: String, payload: String, timestamp: Long) {
        transaction {
            WidgetTable.update({ WidgetTable.id eq id }) {
                it[WidgetTable.lastPayload] = payload
                it[WidgetTable.lastSeenAt]  = timestamp
            }
        }
    }

    // Coalesced persistence: one transaction per 5s cycle, at most one UPDATE
    // per changed widget (instead of one DB write per frame on the read path).
    override fun updateLastPayloadBatch(updates: List<com.jeanloickdt.widget.domain.LastPayloadUpdate>) {
        if (updates.isEmpty()) return
        transaction {
            updates.forEach { u ->
                WidgetTable.update({ WidgetTable.id eq u.widgetId }) {
                    it[WidgetTable.lastPayload] = u.payload
                    it[WidgetTable.lastSeenAt]  = u.at
                }
            }
        }
    }

    // ============================================================
    // Delete a widget
    // ============================================================
    override fun delete(id: String): Boolean {
        return transaction {
            WidgetTable.deleteWhere { WidgetTable.id eq id } > 0
        }
    }

    // ============================================================
    // Delete all widgets of a project — project DELETE cascade
    // ============================================================
    override fun deleteAllByProject(projectId: String) {
        transaction {
            WidgetTable.deleteWhere { WidgetTable.projectId eq projectId }
        }
    }

    // ============================================================
    // Map ResultRow → WidgetRow
    // ============================================================
    private fun ResultRow.toWidgetRow() = WidgetRow(
        id          = this[WidgetTable.id],
        projectId   = this[WidgetTable.projectId],
        ownerId     = this[WidgetTable.ownerId],
        type        = this[WidgetTable.type],
        lastPayload = this[WidgetTable.lastPayload],
        lastSeenAt  = this[WidgetTable.lastSeenAt]
    )
}