/*
 * InstantIoT Server — self-hosted IoT relay for makers.
 * Copyright (C) 2026 InstantIoT
 * Author: Djoufack Tsobeng Jean Loick (@jeanloick_dt)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.jeanloickdt.common

import java.io.File
import java.net.InetAddress
import java.net.NetworkInterface
import java.util.Properties

/**
 * Server configuration — HTTP and TCP ports.
 *
 * The ports are stored in ~/.instantiot/server.properties.
 * If the file does not exist, the default values are used.
 * Port changes require a server restart.
 */
object ServerConfig {

    // Single-source version: read from the resource generated by Gradle
    // (`generateVersionResource` → instantiot-version.properties, injected
    // from `version` in build.gradle.kts). ONE single source of truth.
    // Fallback "0.0.0-dev" only if launched outside the packaged JAR (e.g. tests
    // without processResources) — never in prod.
    private val VERSION: String = runCatching {
        ServerConfig::class.java
            .getResourceAsStream("/instantiot-version.properties")
            ?.use { stream ->
                java.util.Properties().apply { load(stream) }
                    .getProperty("version")
            }
            ?.trim()
            ?.takeIf { it.isNotEmpty() }
    }.getOrNull() ?: "0.0.0-dev"

    /** Root directory of all the server's state files. */
    val instantiotDir: File = File("${System.getProperty("user.home")}/.instantiot").apply {
        mkdirs()
    }

    /** Path of the SQLite DB. Centralized here so a jpackage / systemd
     *  migration does not lose the DB depending on the CWD. */
    val dbFile: File = File(instantiotDir, "instantiot.db")

    private val configFile = File(instantiotDir, "server.properties")

    var httpPort: Int = 8080
        private set

    var tcpPort: Int = 9001
        private set

    /**
     * Server display name — visible in the mDNS Discovery app.
     * Lets a user with 2 servers on the same LAN (living-room Pi,
     * garage Pi…) distinguish them in the app's list.
     *
     * Empty or null → fallback HOSTNAME / "InstantIoT Server" at boot.
     * Restart required to apply (mDNS is published at boot).
     */
    var serverDisplayName: String = ""
        private set

    // ports actually used by the server at startup
    // (do not change after a save — only after a restart)
    var runningHttpPort: Int = 8080
        private set
    var runningTcpPort: Int = 9001
        private set

    /**
     * Called by Application.main after the ports auto-bind — synchronizes
     * the "running ports" with what is actually bound. Used by
     * mDNS, tray, /api/status to announce the correct URL to clients
     * even if we fell back to 8081/9002 etc.
     */
    fun markRunningPorts(http: Int, tcp: Int) {
        runningHttpPort = http
        runningTcpPort = tcp
    }

    // ============================================================
    // HISTORY — Phase 1 (raw numeric)
    // ============================================================

    // ============================================================
    // AUTOMATIC BACKUP — V1
    // ============================================================

    /** Auto backup enabled by default — protects the maker against DB
     *  loss in case of SQLite corruption, a dying disk, etc. */
    var backupEnabled: Boolean = true
        private set

    /** Interval between 2 automatic backups (hours). 24h = once
     *  per day, low impact. Min 1h, no max (but not below
     *  1h to avoid write storms on Pi SD cards). */
    var backupIntervalHours: Int = 24
        private set

    /** Number of backups kept. Beyond that, the oldest are purged
     *  by the post-snapshot cleanup. 30 = ~1 month if daily. */
    var backupRetentionCount: Int = 30
        private set

    /** Snapshots directory — subfolder of instantiotDir to stay
     *  grouped with licence.key, secret.key, instantiot.db. */
    val backupDir: File = File(instantiotDir, "backups").apply { mkdirs() }

    // ============================================================
    // USER REGISTRATION — V1
    // ============================================================

    /** Public registration. **Default false** (secure-by-default):
     *  without it, anyone on the LAN (the app discovers the server via
     *  mDNS) could self-register. The admin opens registration while
     *  onboarding their users then closes it. The admin itself is created
     *  by license activation (separate path), never blocked by this
     *  flag. Gitea/Vaultwarden SIGNUPS_ALLOWED pattern. */
    var registrationOpen: Boolean = false
        private set

    /** Saves the registration flag. Hot-reload — no restart. */
    fun saveRegistrationConfig(open: Boolean) {
        registrationOpen = open
        writeProperties()
    }

    /** Saves the backup config. Hot-reload — no restart required. */
    fun saveBackupConfig(
        enabled: Boolean? = null,
        intervalHours: Int? = null,
        retentionCount: Int? = null
    ) {
        if (enabled != null)        backupEnabled = enabled
        if (intervalHours != null)  backupIntervalHours = intervalHours.coerceAtLeast(1)
        if (retentionCount != null) backupRetentionCount = retentionCount.coerceAtLeast(1)
        writeProperties()
    }

    /**
     * Enables the RAW tier (`widget_history_numeric`). **ON by default** —
     * lets the app zoom in high resolution on windows ≤ 30min
     * without admin config (the chart auto-uses the raw tier when
     * available). Cost bounded by [historyRetentionRawDays] = 48h by
     * default + daily cleanup.
     *
     * When enabled: each numeric sample is buffered and written
     * as-is — no throttle, perfect fidelity for the 1h/6h
     * windows in extended "live" mode.
     *
     * The admin can disable it via PATCH /api/admin/history-config if their
     * setup requires it (e.g. 100+ sensors at 100Hz on a 16GB SD card).
     */
    var historyRawEnabled: Boolean = true
        private set

    /**
     * Retention of RAW rows in `widget_history_numeric` (days).
     *
     * Default **1 day** (24h) — exactly the High Res UI cap on the
     * chart side. No waste: what we store = what we can display.
     * To archive wider windows, the `min/hour/day` tiers
     * (kept 90d/365d/∞) cover all use cases.
     */
    var historyRetentionRawDays: Int = 1
        private set

    /** Retention of opaque rows in `widget_history` (days). */
    var historyRetentionOpaqueDays: Int = 1
        private set

    // ============================================================
    // HISTORY — Aggregated tiers (fed in RAM, flushed every 5s)
    //
    // Blynk-style architecture: the 3 tiers consume the raw
    // samples directly via the RAM TierAggregators, no deferred
    // SQL cascade. Always up to date in real time (lag ≤ 5s).
    // ============================================================

    /** Retention of MINUTE buckets (days). */
    var historyRetentionMinDays: Int = 90
        private set

    /** Retention of HOUR buckets (days). */
    var historyRetentionHourDays: Int = 365
        private set

    /**
     * Retention of DAY buckets (days).
     * `-1` = unlimited (never purged).
     */
    var historyRetentionDayDays: Int = -1
        private set

    val version: String get() = VERSION
    val startedAt: Long = System.currentTimeMillis()

    val uptimeMs: Long get() = System.currentTimeMillis() - startedAt

    /**
     * Resolves the server's LAN IP, favoring the "real" Wi-Fi/Ethernet
     * interface, not a VPN or virtual interface.
     *
     * Why a scoring: on macOS with an active VPN (Cisco, Wireguard,
     * Tailscale, etc.), `getNetworkInterfaces` may return the `utun`
     * tunnel interface BEFORE the `en0` Wi-Fi interface. If we take the
     * 1st found, mDNS binds on the tunnel → multicast `224.0.0.251` → "No
     * route to host" → mDNS down.
     *
     * Filters + scoring:
     *   - Skip: loopback, down, virtual, point-to-point, no multicast
     *   - IP score: 192.168.* (home LAN) > 10.* (corporate LAN) >
     *               172.16-31.* (often VPN/Docker) > other
     *   - Tie-break: interface name (en0 < en1 < etc.)
     */
    val localIp: String get() = try {
        bestLanInterface()?.first ?: InetAddress.getLocalHost().hostAddress
    } catch (_: Exception) {
        "unknown"
    }

    /**
     * Returns (ipAddress, interfaceName) of the "best" LAN interface
     * found, or null if no valid candidate.
     */
    fun bestLanInterface(): Pair<String, String>? {
        val candidates = NetworkInterface.getNetworkInterfaces().asSequence()
            .filter { iface ->
                try {
                    iface.isUp &&
                        !iface.isLoopback &&
                        !iface.isVirtual &&
                        !iface.isPointToPoint &&
                        iface.supportsMulticast()
                } catch (_: Exception) { false }
            }
            .flatMap { iface ->
                iface.inetAddresses.asSequence()
                    .filter { it is java.net.Inet4Address && !it.isLoopbackAddress }
                    .map { it.hostAddress to iface.name }
            }
            .toList()

        if (candidates.isEmpty()) return null

        // Score: higher = better
        fun score(ip: String, name: String): Int {
            var s = 0
            if (ip.startsWith("192.168.")) s += 100
            else if (ip.startsWith("10."))  s += 80
            else if (ip.startsWith("172.")) {
                // 172.16-31 = private. Often docker/VPN — lower priority.
                val second = ip.split(".").getOrNull(1)?.toIntOrNull() ?: 0
                if (second in 16..31) s += 30
            }
            // Prefer classic "physical" interfaces
            if (name.startsWith("en"))  s += 10  // macOS Wi-Fi/Ethernet
            if (name.startsWith("eth")) s += 10  // Linux Ethernet
            if (name.startsWith("wl"))  s += 8   // Linux Wi-Fi
            // Penalize tunnel / virtual interfaces
            if (name.startsWith("utun")) s -= 50
            if (name.startsWith("tun"))  s -= 50
            if (name.startsWith("tap"))  s -= 50
            if (name.contains("docker")) s -= 50
            if (name.startsWith("br-"))  s -= 30  // Linux bridge
            return s
        }

        return candidates.maxByOrNull { (ip, name) -> score(ip, name) }
    }

    val dbSizeBytes: Long get() = try {
        dbFile.length()
    } catch (_: Exception) {
        0L
    }

    /**
     * Loads the config from the properties file.
     * Called at startup before launching the servers.
     */
    fun load() {
        if (!configFile.exists()) {
            // first launch — create the file with the default values
            save()
            runningHttpPort = httpPort
            runningTcpPort = tcpPort
            return
        }

        try {
            val props = Properties()
            configFile.inputStream().use { props.load(it) }
            httpPort = props.getProperty("http.port", "8080").toIntOrNull() ?: 8080
            tcpPort = props.getProperty("tcp.port", "9001").toIntOrNull() ?: 9001

            // History — iWidgets rework (Blynk-style architecture)
            historyRawEnabled = props.getProperty("history.raw.enabled", "true")
                .toBooleanStrictOrNull() ?: true
            historyRetentionRawDays = props.getProperty("history.retention.raw.days", "1")
                .toIntOrNull()?.coerceAtLeast(1) ?: 1
            historyRetentionOpaqueDays = props.getProperty("history.retention.opaque.days", "1")
                .toIntOrNull()?.coerceAtLeast(1) ?: 1

            // Aggregated tiers
            historyRetentionMinDays = props.getProperty("history.retention.min.days", "90")
                .toIntOrNull()?.coerceAtLeast(1) ?: 90
            historyRetentionHourDays = props.getProperty("history.retention.hour.days", "365")
                .toIntOrNull()?.coerceAtLeast(1) ?: 365
            historyRetentionDayDays = props.getProperty("history.retention.day.days", "-1")
                .toIntOrNull() ?: -1
            serverDisplayName = props.getProperty("server.displayName", "").trim()
            backupEnabled = props.getProperty("backup.enabled", "true")
                .toBooleanStrictOrNull() ?: true
            backupIntervalHours = props.getProperty("backup.interval.hours", "24")
                .toIntOrNull()?.coerceAtLeast(1) ?: 24
            backupRetentionCount = props.getProperty("backup.retention.count", "30")
                .toIntOrNull()?.coerceAtLeast(1) ?: 30
            registrationOpen = props.getProperty("registration.open", "false")
                .toBooleanStrictOrNull() ?: false
        } catch (_: Exception) {
            // corrupted file — keep the default values
        }
        // freeze the startup ports — they no longer change after a save
        runningHttpPort = httpPort
        runningTcpPort = tcpPort
    }

    /**
     * Saves the ports to the properties file.
     * The server must be restarted to apply the changes.
     */
    fun save(
        newHttpPort: Int? = null,
        newTcpPort: Int? = null,
        newServerDisplayName: String? = null
    ) {
        if (newHttpPort != null) httpPort = newHttpPort
        if (newTcpPort != null) tcpPort = newTcpPort
        if (newServerDisplayName != null) serverDisplayName = newServerDisplayName.trim()
        writeProperties()
    }

    /**
     * Saves the history parameters. Any `null` is ignored
     * (partial update). No restart needed — the values
     * are re-read on each cleanup / write cycle by the next iter.
     */
    fun saveHistoryConfig(
        rawEnabled: Boolean? = null,
        retentionRawDays: Int? = null,
        retentionOpaqueDays: Int? = null,
        retentionMinDays: Int? = null,
        retentionHourDays: Int? = null,
        retentionDayDays: Int? = null
    ) {
        if (rawEnabled != null)          historyRawEnabled          = rawEnabled
        if (retentionRawDays != null)    historyRetentionRawDays    = retentionRawDays.coerceAtLeast(1)
        if (retentionOpaqueDays != null) historyRetentionOpaqueDays = retentionOpaqueDays.coerceAtLeast(1)
        if (retentionMinDays != null)    historyRetentionMinDays    = retentionMinDays.coerceAtLeast(1)
        if (retentionHourDays != null)   historyRetentionHourDays   = retentionHourDays.coerceAtLeast(1)
        if (retentionDayDays != null)    historyRetentionDayDays    = retentionDayDays // -1 allowed = unlimited
        writeProperties()
    }

    private fun writeProperties() {
        configFile.parentFile.mkdirs()
        val props = Properties()
        props.setProperty("http.port", httpPort.toString())
        props.setProperty("tcp.port", tcpPort.toString())
        props.setProperty("history.raw.enabled", historyRawEnabled.toString())
        props.setProperty("history.retention.raw.days", historyRetentionRawDays.toString())
        props.setProperty("history.retention.opaque.days", historyRetentionOpaqueDays.toString())
        props.setProperty("history.retention.min.days", historyRetentionMinDays.toString())
        props.setProperty("history.retention.hour.days", historyRetentionHourDays.toString())
        props.setProperty("history.retention.day.days", historyRetentionDayDays.toString())
        props.setProperty("server.displayName", serverDisplayName)
        props.setProperty("backup.enabled", backupEnabled.toString())
        props.setProperty("backup.interval.hours", backupIntervalHours.toString())
        props.setProperty("backup.retention.count", backupRetentionCount.toString())
        props.setProperty("registration.open", registrationOpen.toString())
        configFile.outputStream().use { props.store(it, "InstantIoT Server Configuration") }
    }
}