/*
 * InstantIoT Server — self-hosted IoT relay for makers.
 * Copyright (C) 2026 Djoufack Tsobeng Jean Loick (InstantIoT)
 * Author: Djoufack Tsobeng Jean Loick (@jeanloick_dt)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// relay/ConnectionRegistry.kt
package com.jeanloickdt.relay

import com.jeanloickdt.device.domain.DeviceRow
import io.ktor.network.sockets.Socket
import io.ktor.utils.io.ByteWriteChannel
import io.ktor.websocket.*
import kotlinx.coroutines.CoroutineScope
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.CopyOnWriteArrayList

// Type aliases to clarify the map keys
typealias UserId   = String
typealias DeviceId = String
typealias WidgetId = String

// App session — one WebSocket session per app connection
data class AppSession(
    val userId: UserId,
    val session: WebSocketSession,
    /**
     * Send buffer for this session. EVERY device→app send goes through it —
     * a direct `session.send` from the device read coroutine would suspend on
     * a zombie app and stall that device. Cf. [AppOutbox].
     */
    val outbox: AppOutbox,
    /**
     * UUID v4 generated by the app at install time (persisted locally). Identifies
     * this installation for dedup: a previous session is only kicked
     * if it comes from the **same install** (same `connectionInstanceId`),
     * thereby allowing several devices of the same user to coexist on
     * the same project.
     */
    val connectionInstanceId: String,
    var activeProjectId: String? = null,  // currently open project — changes dynamically
    // History subscriptions: map widgetId → granularity ("minute" | "hour" | "day").
    // Set by the app via {"type":"subscribe_history","widgets":[...]}, read by the
    // bucket_updated broadcaster. ConcurrentHashMap: written by the WS read loop,
    // read by the broadcaster.
    val historySubs: ConcurrentHashMap<String, String> = ConcurrentHashMap()
)

// Device session — one TCP session per connected device.
// `socket` is the ktor-network non-blocking socket; liveness is read via
// `socket.socketContext.isActive` (ktor Socket has no `isClosed`).
data class DeviceSession(
    val device: DeviceRow,
    val socket: Socket
)

/**
 * The live PHYSICAL connections of THIS node: app WebSocket sessions, device
 * TCP sessions and their write outboxes.
 *
 * Local by nature — a socket lives on exactly one node, which will stay true
 * even in a future multi-node deployment (only presence/routing get shared,
 * never the sockets themselves). Injected by constructor, never global.
 */
class ConnectionRegistry {

    // userId → list of WebSocket app sessions (multi-device: phone + tablet)
    val appSessions = ConcurrentHashMap<UserId, CopyOnWriteArrayList<AppSession>>()

    // deviceId → TCP device session
    val deviceSessions = ConcurrentHashMap<DeviceId, DeviceSession>()

    // deviceId → serialization outbox for TCP writes (see DeviceOutbox)
    val deviceOutboxes = ConcurrentHashMap<DeviceId, DeviceOutbox>()

    // register an app session — supports multiple connections per user
    fun registerApp(
        userId: UserId,
        session: WebSocketSession,
        connectionInstanceId: String
    ): AppSession {
        val appSession = AppSession(
            userId = userId,
            session = session,
            outbox = AppOutbox(userId, session),
            connectionInstanceId = connectionInstanceId
        )
        appSessions.computeIfAbsent(userId) { CopyOnWriteArrayList() }.add(appSession)
        return appSession
    }

    // change the active project of a specific session
    fun setActiveProject(appSession: AppSession, projectId: String) {
        appSession.activeProjectId = projectId
    }

    // remove a specific app session — by WebSocketSession reference
    fun unregisterApp(userId: UserId, session: WebSocketSession) {
        val sessions = appSessions[userId] ?: return
        // Close the outbox before dropping the session: its consumers end with
        // the session scope anyway, but this releases the channels and logs the
        // drop count for that session.
        sessions.firstOrNull { it.session === session }?.outbox?.close()
        sessions.removeIf { it.session === session }
        if (sessions.isEmpty()) {
            appSessions.remove(userId)
        }
    }

    /**
     * Finds the registered [AppSession] wrapping this raw WebSocket, if any.
     * Needed by targeted sends (`command_failed`), which only hold the session
     * but must go through its outbox like every other device→app write.
     */
    fun findAppSession(session: WebSocketSession): AppSession? =
        appSessions.values.firstNotNullOfOrNull { sessions ->
            sessions.firstOrNull { it.session === session }
        }

    // all apps watching a given project — iterates over every session
    fun getAppSessionsForProject(projectId: String): List<AppSession> {
        return appSessions.values.flatMap { sessions ->
            sessions.filter { it.activeProjectId == projectId }
        }
    }

    // register a device session + create its outbox.
    // The provided `scope` governs the outbox's consumer coroutine —
    // the long-lived relay scope, so it outlives the per-connection coroutine.
    fun registerDevice(
        deviceId: DeviceId,
        device: DeviceRow,
        socket: Socket,
        writeChannel: ByteWriteChannel,
        scope: CoroutineScope
    ) {
        deviceSessions[deviceId] = DeviceSession(device, socket)
        // Close any previous outbox (fast reconnect of the same deviceId)
        // to avoid leaking a consumer coroutine.
        deviceOutboxes.remove(deviceId)?.close()
        deviceOutboxes[deviceId] = DeviceOutbox(
            deviceId     = deviceId,
            writeChannel = writeChannel,
            scope        = scope
        )
    }

    // remove a device session — disconnection. Closes the outbox (→ the
    // consumer coroutine exits cleanly) and frees the references.
    fun unregisterDevice(deviceId: DeviceId) {
        deviceSessions.remove(deviceId)
        deviceOutboxes.remove(deviceId)?.close()
    }

    // find a device's session by its ID
    fun getDeviceSession(deviceId: DeviceId): DeviceSession? {
        return deviceSessions[deviceId]
    }
}
