/*
 * InstantIoT Server — self-hosted IoT relay for makers.
 * Copyright (C) 2026 Djoufack Tsobeng Jean Loick (InstantIoT)
 * Author: Djoufack Tsobeng Jean Loick (@jeanloick_dt)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// relay/ConnectionRegistry.kt
package com.jeanloickdt.relay

import com.jeanloickdt.device.domain.DeviceRow
import io.ktor.network.sockets.Socket
import io.ktor.utils.io.ByteWriteChannel
import io.ktor.websocket.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.launch
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.CopyOnWriteArrayList

// Type aliases to clarify the map keys
typealias UserId   = String
typealias DeviceId = String
typealias WidgetId = String

// App session — one WebSocket session per app connection
data class AppSession(
    val userId: UserId,
    val session: WebSocketSession,
    /**
     * Send buffer for this session. EVERY device→app send goes through it —
     * a direct `session.send` from the device read coroutine would suspend on
     * a zombie app and stall that device. Cf. [AppOutbox].
     */
    val outbox: AppOutbox,
    /**
     * UUID v4 generated by the app at install time (persisted locally). Identifies
     * this installation for dedup: a previous session is only kicked
     * if it comes from the **same install** (same `connectionInstanceId`),
     * thereby allowing several devices of the same user to coexist on
     * the same project.
     */
    val connectionInstanceId: String,
    var activeProjectId: String? = null  // currently open project — changes dynamically
)

// Device session — one TCP session per connected device.
// `socket` is the ktor-network non-blocking socket; liveness is read via
// `socket.socketContext.isActive` (ktor Socket has no `isClosed`).
data class DeviceSession(
    val device: DeviceRow,
    val socket: Socket
)

/**
 * The live PHYSICAL connections of THIS node: app WebSocket sessions, device
 * TCP sessions and their write outboxes.
 *
 * Local by nature — a socket lives on exactly one node, which will stay true
 * even in a future multi-node deployment (only presence/routing get shared,
 * never the sockets themselves). Injected by constructor, never global.
 */
class ConnectionRegistry {

    // userId → list of WebSocket app sessions (multi-device: phone + tablet)
    val appSessions = ConcurrentHashMap<UserId, CopyOnWriteArrayList<AppSession>>()

    // deviceId → TCP device session
    val deviceSessions = ConcurrentHashMap<DeviceId, DeviceSession>()

    // deviceId → serialization outbox for TCP writes (see DeviceOutbox)
    val deviceOutboxes = ConcurrentHashMap<DeviceId, DeviceOutbox>()

    /**
     * Les sessions app par projet regarde.
     *
     * `getAppSessionsForProject` parcourait TOUTES les sessions du noeud a
     * chaque trame de carte acceptee et a chaque evenement de controle : N
     * sessions faisaient de chaque trame un balayage en O(N). Un compte
     * pouvait en ouvrir sans limite (l'identifiant d'installation est choisi
     * par le client), et des milliers de sessions parquees ralentissaient
     * toutes les cartes. L'index est tenu a l'enregistrement, au changement
     * de projet et au depart.
     */
    private val byProject = ConcurrentHashMap<String, CopyOnWriteArrayList<AppSession>>()

    /** La porte des sessions app, le pendant de celle des cartes. */
    val appGate = ConnectionGate(MAX_APP_SESSIONS)

    /**
     * Register an app session. Several per user, but not without limit:
     * `null` when this account already holds [MAX_SESSIONS_PER_USER].
     */
    fun registerApp(
        userId: UserId,
        session: WebSocketSession,
        connectionInstanceId: String
    ): AppSession? {
        val mine = appSessions.computeIfAbsent(userId) { CopyOnWriteArrayList() }
        if (mine.size >= MAX_SESSIONS_PER_USER) return null
        val appSession = AppSession(
            userId = userId,
            session = session,
            outbox = AppOutbox(userId, session),
            connectionInstanceId = connectionInstanceId
        )
        mine.add(appSession)
        return appSession
    }

    // change the active project of a specific session, and keep the index with it
    fun setActiveProject(appSession: AppSession, projectId: String) {
        appSession.activeProjectId?.let { previous -> byProject[previous]?.remove(appSession) }
        appSession.activeProjectId = projectId
        byProject.computeIfAbsent(projectId) { CopyOnWriteArrayList() }.add(appSession)
    }

    // remove a specific app session — by WebSocketSession reference
    fun unregisterApp(userId: UserId, session: WebSocketSession) {
        val sessions = appSessions[userId] ?: return
        // Close the outbox before dropping the session: its consumers end with
        // the session scope anyway, but this releases the channels and logs the
        // drop count for that session.
        val gone = sessions.firstOrNull { it.session === session }
        gone?.outbox?.close()
        gone?.activeProjectId?.let { projectId ->
            byProject[projectId]?.let { list ->
                list.remove(gone)
                if (list.isEmpty()) byProject.remove(projectId, list)
            }
        }
        sessions.removeIf { it.session === session }
        if (sessions.isEmpty()) {
            appSessions.remove(userId)
        }
    }

    /**
     * Ferme toutes les sessions app d'un compte, avec la raison.
     *
     * Le plancher de version tue le jeton vole a la requete suivante, mais il
     * ne fermait aucune session deja ouverte : « changer mon mot de passe »
     * laissait le voleur connecte tant que sa socket tenait, avec
     * write_signal vers les cartes. La fermeture est LANCEE, jamais attendue :
     * `close` suspend, et l'appelant est une route HTTP.
     *
     * @return combien de sessions ont ete fermees.
     */
    fun closeAppSessions(userId: UserId, reason: String): Int {
        val sessions = appSessions[userId] ?: return 0
        var closed = 0
        for (s in sessions) {
            closed++
            s.session.launch {
                runCatching { s.session.close(CloseReason(CloseReason.Codes.VIOLATED_POLICY, reason)) }
            }
        }
        return closed
    }

    /**
     * Finds the registered [AppSession] wrapping this raw WebSocket, if any.
     * Needed by targeted sends (`command_failed`), which only hold the session
     * but must go through its outbox like every other device→app write.
     */
    fun findAppSession(session: WebSocketSession): AppSession? =
        appSessions.values.firstNotNullOfOrNull { sessions ->
            sessions.firstOrNull { it.session === session }
        }

    /** Les apps qui regardent ce projet : par l'index, plus par balayage. */
    fun getAppSessionsForProject(projectId: String): List<AppSession> =
        byProject[projectId]?.toList().orEmpty()

    // register a device session + create its outbox.
    // The provided `scope` governs the outbox's consumer coroutine —
    // the long-lived relay scope, so it outlives the per-connection coroutine.
    fun registerDevice(
        deviceId: DeviceId,
        device: DeviceRow,
        socket: Socket,
        writeChannel: ByteWriteChannel,
        scope: CoroutineScope
    ) {
        val previous = deviceSessions.put(deviceId, DeviceSession(device, socket))
        // Close any previous outbox (fast reconnect of the same deviceId)
        // to avoid leaking a consumer coroutine.
        deviceOutboxes.remove(deviceId)?.close()
        // …and the previous SOCKET — the outbox half of this was always here,
        // the socket half was the missing symmetry. Closing it wakes the old
        // reader immediately (no 90 s zombie window); its cleanup then fails
        // the ownership check above and touches nothing. ONLY safe because
        // that check exists — without it this line would make the race fire
        // on every reconnect instead of occasionally.
        runCatching { previous?.socket?.close() }
        deviceOutboxes[deviceId] = DeviceOutbox(
            deviceId     = deviceId,
            writeChannel = writeChannel,
            scope        = scope
        )
    }

    // remove a device session — disconnection. Closes the outbox (→ the
    // consumer coroutine exits cleanly) and frees the references.
    /**
     * Removes the session ONLY if [mine] is the socket still occupying the
     * slot, and says whether it was.
     *
     * The ownership check is the fix for a production race: a zombie
     * connection's timeout fires AFTER the board has reconnected, and its
     * cleanup used to remove the NEW session — telemetry kept flowing (the
     * reader holds locals) but every command failed with DEVICE_OFFLINE until
     * the next physical reconnect, for hours.
     *
     * `===` (reference identity), never `==`: [DeviceSession] is a data class,
     * and two different connections of the same board carry an equal
     * [DeviceRow] — content equality would declare the zombie the owner.
     *
     * `computeIfPresent` makes test-and-remove atomic. A get-then-remove would
     * shrink the race window instead of closing it — same bug, a thousand
     * times rarer and a thousand times harder to find.
     */
    fun unregisterDevice(deviceId: DeviceId, mine: Socket): Boolean {
        var owned = false
        deviceSessions.computeIfPresent(deviceId) { _, s ->
            if (s.socket === mine) { owned = true; null } else s   // null ⇒ atomic removal
        }
        if (owned) deviceOutboxes.remove(deviceId)?.close()
        return owned
    }

    // find a device's session by its ID
    fun getDeviceSession(deviceId: DeviceId): DeviceSession? {
        return deviceSessions[deviceId]
    }

    companion object {
        /** Huit sessions par compte : un telephone, une tablette, deux navigateurs, et de la marge. Pas un script. */
        const val MAX_SESSIONS_PER_USER = 8
        /** Toutes sessions app confondues sur ce noeud ; chacune tient trois coroutines et ses tampons. */
        const val MAX_APP_SESSIONS = 5_000
    }
}
