/*
 * InstantIoT Server — self-hosted IoT relay for makers.
 * Copyright (C) 2026 Djoufack Tsobeng Jean Loick (InstantIoT)
 * Author: Djoufack Tsobeng Jean Loick (@jeanloick_dt)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// relay/SessionRegistry.kt
package com.jeanloickdt.relay

import com.jeanloickdt.device.domain.DeviceRow
import io.ktor.websocket.*
import kotlinx.coroutines.CoroutineScope
import java.net.Socket
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.ConcurrentLinkedQueue
import java.util.concurrent.CopyOnWriteArrayList

// Type aliases to clarify the map keys
typealias UserId   = String
typealias DeviceId = String
typealias WidgetId = String

// App session — one WebSocket session per app connection
data class AppSession(
    val userId: UserId,
    val session: WebSocketSession,
    /**
     * UUID v4 generated by the app at install time (persisted locally). Identifies
     * this installation for dedup: a previous session is only kicked
     * if it comes from the **same install** (same `connectionInstanceId`),
     * thereby allowing several devices of the same user to coexist on
     * the same project.
     */
    val connectionInstanceId: String,
    var activeProjectId: String? = null,  // currently open project — changes dynamically
    // History subscriptions: map widgetId → granularity ("minute" | "hour" | "day").
    // Set by the app via message {"type":"subscribe_history","widgets":[...]}. Filtered
    // by the bucket_updated broadcaster to only broadcast the buckets the app
    // has explicitly requested (= charts in preset mode with FromWidget source +
    // open history bottom sheets). Avoids wasting network when some
    // widgets have no active chart on the UI side.
    //
    // Thread-safe: mutable Map accessed from the read loop (write) and the bucket
    // broadcaster (read). Safeguard: wrap in synchronized blocks or
    // use ConcurrentHashMap. Choice: ConcurrentHashMap to keep it simple.
    val historySubs: java.util.concurrent.ConcurrentHashMap<String, String> = java.util.concurrent.ConcurrentHashMap()
)

// Device session — one TCP session per connected device
data class DeviceSession(
    val device: DeviceRow,
    val socket: Socket
)

// History entry — buffer before SQLite flush
data class HistoryEntry(
    val widgetId: WidgetId,
    val projectId: String,
    val ownerId: String,
    val payload: String,
    val recordedAt: Long
)

// **Numeric** history entry — buffer before SQLite flush
// Populated in parallel with HistoryEntry when FrameParser.extractNumericValue
// returns a decodable sample (gauge/metric/level/slider/chart).
data class NumericHistoryEntry(
    val widgetId: WidgetId,
    val projectId: String,
    val ownerId: String,
    val seriesId: String?,
    val value: Double,
    val recordedAt: Long
)

object SessionRegistry {

    // userId → list of WebSocket app sessions (multi-device: phone + tablet)
    val appSessions = ConcurrentHashMap<UserId, CopyOnWriteArrayList<AppSession>>()

    // deviceId → TCP device session
    val deviceSessions = ConcurrentHashMap<DeviceId, DeviceSession>()

    // deviceId → serialization outbox for TCP writes (see DeviceOutbox)
    val deviceOutboxes = ConcurrentHashMap<DeviceId, DeviceOutbox>()

    // widgetId → last payload received — fast access without DB
    val lastPayloads = ConcurrentHashMap<WidgetId, String>()

    // history buffer — flushed every 5s to SQLite WAL batch
    val historyBuffer = ConcurrentLinkedQueue<HistoryEntry>()

    // numeric history buffer — populated ONLY if the admin enabled
    // the raw tier (ServerConfig.historyRawEnabled). Flushed every 5s to
    // widget_history_numeric.
    //
    // No more throttle: since the iWidgets history rework, we
    // favor a tiered-aggregation architecture where the min/hour/day tiers
    // (always active via the RAM aggregators) are enough to
    // visualize the signal envelope. The raw tier, when enabled,
    // keeps ALL samples without server-side filtering — protection
    // against abuse on the sketch side is documented, not enforced.
    val numericHistoryBuffer = ConcurrentLinkedQueue<NumericHistoryEntry>()

    // RAM cache of widgetIds (= protocolId) already known in the DB.
    // Used by auto-register in DeviceRelay: a widgetId already in
    // the Set → no DB hit, otherwise INSERT OR IGNORE + add to the Set.
    // Populated at startup via `seedKnownWidgets()` + incrementally.
    val knownWidgetIds: MutableSet<WidgetId> = java.util.concurrent.ConcurrentHashMap.newKeySet()

    // register an app session — supports multiple connections per user
    fun registerApp(
        userId: UserId,
        session: WebSocketSession,
        connectionInstanceId: String
    ): AppSession {
        val appSession = AppSession(userId, session, connectionInstanceId)
        appSessions.computeIfAbsent(userId) { CopyOnWriteArrayList() }.add(appSession)
        return appSession
    }

    // change the active project of a specific session
    fun setActiveProject(appSession: AppSession, projectId: String) {
        appSession.activeProjectId = projectId
    }

    // remove a specific app session — by WebSocketSession reference
    fun unregisterApp(userId: UserId, session: WebSocketSession) {
        val sessions = appSessions[userId] ?: return
        sessions.removeIf { it.session === session }
        if (sessions.isEmpty()) {
            appSessions.remove(userId)
        }
    }

    // all apps watching a given project — iterates over every session
    fun getAppSessionsForProject(projectId: String): List<AppSession> {
        return appSessions.values.flatMap { sessions ->
            sessions.filter { it.activeProjectId == projectId }
        }
    }

    // register a device session + create its outbox.
    // The provided `scope` governs the outbox's consumer coroutine —
    // typically the Ktor `applicationScope` (long-lived).
    fun registerDevice(deviceId: DeviceId, device: DeviceRow, socket: Socket, scope: CoroutineScope) {
        deviceSessions[deviceId] = DeviceSession(device, socket)
        // Close any previous outbox (fast reconnect of the same deviceId)
        // to avoid leaking a consumer coroutine.
        deviceOutboxes.remove(deviceId)?.close()
        deviceOutboxes[deviceId] = DeviceOutbox(
            deviceId = deviceId,
            socket   = socket,
            scope    = scope
        )
    }

    // remove a device session — disconnection. Closes the outbox (→ the
    // consumer coroutine exits cleanly) and frees the references.
    fun unregisterDevice(deviceId: DeviceId) {
        deviceSessions.remove(deviceId)
        deviceOutboxes.remove(deviceId)?.close()
    }

    // find a device's session by its ID
    fun getDeviceSession(deviceId: DeviceId): DeviceSession? {
        return deviceSessions[deviceId]
    }
}